# Site settings
title: GREENIFY
header-img: img/home-bg.jpg
email: heeraj123@gmail.com
description: "Plant a tree and Save the world!"
baseurl: ""
url: "http://i4info.in/"
twitter_username: heeraj123
github_username:  heeraj123
facebook_username:  heeraj123

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
